# Site settings
title: Pointing to the Moon
description: Blog of Fan
baseurl: "" 
url: "https://jwoa1022.github.io/" 

# GitHub User settings
username: Fan
github_username: JWOA
user_description: Fan
user_title: EE Undergraduate
email: 2522213745@qq.com

# Blog Author settings
author:
  name:           Fan Zhang
  picture:        
  email:          2522213745@qq.com
  description:    Fan
  twitter:
  facebook:
  github:         https://github.com/JWOA1022
  linkedin:
  # # If you're forking this site, make sure you delete this entry!
  clustrmap:      MlqUzlcZFdHetSQuxml5oHyt9RwVjZrsGbvyaRpMwgU 
  # If you're forking this site, make sure you delete this entry!


# markdown
# markdown: kramdown

# future: true
  
# kramdown:
#  footnote_nr: 1
#  entity_output: as_char
#  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#   # Use existing pygments syntax highlighting css
#   css_class: 'highlight'
#  span:
#   line_numbers: false
#  block:
#   line_numbers: true
#   start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: /:year/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.tex"
 - "*.aux"
 - "*.log"
 - "*.out"
 - "*.gz"
 - "*.toc"
 - "*.bib"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
 - "*.source.*"